name: End To End Test

on:
  workflow_run:
    workflows: ["Staging CI/CD"]
    branches: [staging]
    types:
      - completed

jobs:
  run_end_to_end_tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: staging
    name: End To End Test Run
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          ref: 'staging'
      - name: Create env file
        run: |
          touch ./e2e/.env
          echo LOGIN=${{secrets.LOGIN}} >> ./e2e/.env
          echo PASSWORD=${{secrets.PASSWORD}} >> ./e2e/.env
          cat ./e2e/.env
      - name: Install Dependencies
        run: |
          npm i
          npx playwright install-deps
        env:
          PRIVATE_PKG_PAT: ${{ secrets.PRIVATE_PKG_PAT}}
      - name: Run End To End Tests
        run: npm run e2e
      - name: Deploy To Production
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: mhoffner/my-first-static-web-app
          event-type: push-staging-to-main