name: End To End Test

on:
  workflow_run:
    workflows: ["Staging CI/CD"]
    branches: [staging]
    types:
      - completed

jobs:
  run_end_to_end_tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: End To End Test Run
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
    # RUN THE TESTS HERE
      - name: Deploy To Production
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: mhoffner/my-first-static-web-app
          event-type: push-staging-to-main