name: Production CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]
    branches:
      - main

jobs:

  check_pull_elegible_job:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Check for Updated Release Number
        uses: kriasoft/check-version@v1

  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MODE: ${{secrets.MODE}}
          directory: "./"
          file_name: ".env"
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_MUSHROOM_0810F7E0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
          app_build_command: "npm test && npm run build"
        env:
          PRIVATE_PKG_PAT: ${{ secrets.PRIVATE_PKG_PAT}}
      - name: Get Release Number
        id: new-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.new-version.outputs.current-version}}
          release_name: Release ${{ steps.new-version.outputs.current-version}}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_MUSHROOM_0810F7E0F }}
          action: "close"
