name: Version Check

on:
  push:
    branches:
      - staging
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - staging

jobs:

  check_pull_elegible_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with: 
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
      - name: Fail if unchanged
        if: steps.check.outputs.changed != 'true'
        run: |
          'echo "No version change detected"' |
          exit 1